# Generated by Django 2.1.5 on 2022-01-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220128_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
    ]
